languageCode = "en-gb"
title = "Göktuğ's Elisp Website"
#baseurl = "http://elisp.gkayaalp.com/"
author = "Göktuğ Kayaalp"
uglyURLs = true
disablePathToLower = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLs = false
relativeURLs = true
