languageCode = "en-gb"
title = "Göktuğ's Elisp Website"
baseurl = "http://elisp.gkayaalp.com/"
author = "Göktuğ Kayaalp"
uglyURLs = true
publishDir = "../cadadr.github.io/elisp"
disablePathToLower = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLs = false
relativeURLs = true

[Social]
  github = "cadadr"

[Params]
  description = "My elisp"
  footer = "this is a footer"
